version: '3'
volumes:
  db_data:
  node_modules:
  # nginx_error_logs:


services:
  app:
    build:
      context: app/
      dockerfile: .devcontainer/Dockerfile.dev
    container_name: "app"
    ports:
      - "127.0.0.1:3000:3000"
    tty: true
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/app/node_modules
    command:
      - 'sh'
      - '-c'
      - >-
        npm run dev
  
  api:
    build:
      context: api/
      dockerfile: .devcontainer/Dockerfile.dev
    container_name: "api"
    ports:
      - "127.0.0.1:8080:8080"
    tty: true
    volumes:
      - .:/workspace:cached
    environment:
      - DB_HOST=mariadb
      - DB_USER=appuser
      - DB_PASSWOR=password
      - DB_DATABASE=message
      - DB_PORT=3306
      - JWT_SECRET=devjwtsecret
      - NODE_ENV=development
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=message
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3306
    container_name: mariadb
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - "8888:8080"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./nginx/cert/:/etc/certs/:ro
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    tty: true
    environment:
      TZ: Asia/Tokyo
